# -*- coding: utf-8 -*-

"""
Simulator Module.

Defines the Simulator class.
Receives the phenomenological model, calls the CasadiTranspiler, and solves
the Differential-Algebraic Equation (DAE) system over time using CasADi's
native integrators, or resolves steady-state conditions using rootfinders. 
Optimized with Lazy Compilation, Auto-Fallback rules, and Automatic Cleanup 
of temporary C files.
"""

import os
import glob
import warnings

import casadi as ca
import numpy as np

import antares.core.GLOBAL_CFG as cfg
from antares.backend.transpiler import CasadiTranspiler
from antares.core.error_definitions import (
    AbsentRequiredObjectError,
    DegreesOfFreedomError,
    UnexpectedValueError,
)
from antares.core.results import Results


class Simulator:
    """
    Orchestrates the numerical resolution of the mathematical model.
    Bridges the declarative Model abstractions with the high-performance 
    CasADi backend. Supports both dynamic integration (transients) and 
    steady-state rootfinding, along with automatic housekeeping of compilation artifacts.
    """

    def __init__(self, model, solver_type=None, check_dof=None):
        """
        Instantiates the Simulator. Prepares the simulation by transpiling the model
        and setting up the ground for the CasADi solver.

        :param Model model: The model object to be simulated. Must be fully declared.
        :param str solver_type: The type of CasADi integrator to use. If None, falls 
                                back to the global DEFAULT_INTEGRATOR (usually 'idas').
        :param bool check_dof: Flag to enable/disable DOF validation at compile time. 
                               If None, delegates to GLOBAL_CFG.PERFORM_DOF_CHECK.
        """
        self.model = model

        # Applies global configuration if no specific solver is requested
        self.solver_type = (
            solver_type if solver_type is not None else getattr(cfg, "DEFAULT_INTEGRATOR", "idas")
        )

        if self.solver_type not in ["idas", "cvodes", "collocation", "rk"]:
            if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
                warnings.warn(
                    f"Solver type '{self.solver_type}' might not be natively supported. "
                    f"Proceed with caution."
                )

        self.transpiler = CasadiTranspiler(model)

        if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
            print(f"Transpiling model '{self.model.name}' to CasADi representation...")

        # 1. Transpile the mathematical AST into CasADi graph
        self.dae_structure = self.transpiler.transpile()

        # 2. VERIFICATION OF DEGREES OF FREEDOM (Fail-Fast: Compile time)
        do_dof_check = check_dof if check_dof is not None else getattr(cfg, "PERFORM_DOF_CHECK", True)
        if do_dof_check:
            self._check_degrees_of_freedom()

        # Integrator options injected from GLOBAL_CFG
        self.solver_opts = {
            "calc_ic": True,
            "reltol": getattr(cfg, "DEFAULT_RELATIVE_TOLERANCE", 1e-6),
            "abstol": getattr(cfg, "DEFAULT_ABSOLUTE_TOLERANCE", 1e-8),
        }

        # Attributes for Lazy Compilation
        self._integrator = None
        self._rootfinder = None
        self._last_t_span = None
        
        # Tracking generated filenames for cleanup
        self._compilation_prefixes = ["jit_", "tmp_casadi_"]

    def _cleanup_compilation_files(self):
        """
        Scans the current directory for temporary compilation artifacts (.c, .o, .so, .dll)
        generated by the CasADi shell compiler and removes them if the global 
        configuration KEEP_TEMPORARY_COMPILATION_FILES is set to False.
        """
        keep_files = getattr(cfg, "KEEP_TEMPORARY_COMPILATION_FILES", False)
        
        if keep_files:
            return

        extensions = ["*.c", "*.o", "*.so", "*.dll"]
        files_removed = 0

        for prefix in self._compilation_prefixes:
            for ext in extensions:
                pattern = f"{prefix}{ext}"
                for filepath in glob.glob(pattern):
                    try:
                        os.remove(filepath)
                        files_removed += 1
                    except OSError:
                        # Files might be locked by the OS temporarily
                        pass

        if files_removed > 0 and getattr(cfg, "VERBOSITY_LEVEL", 1) >= 2:
            print(f"[DEBUG] Housekeeping: {files_removed} temporary compilation files removed.")

    def _check_degrees_of_freedom(self):
        """
        Validates the mathematical closure of the system by calculating 
        the Degrees of Freedom (DOF) of the transpiled computational graph.

        :raises DegreesOfFreedomError: If total variables and total equations do not match.
        """
        n_x = self.dae_structure["x"].size1() if "x" in self.dae_structure else 0
        n_z = self.dae_structure["z"].size1() if "z" in self.dae_structure else 0
        total_vars = n_x + n_z

        n_ode = self.dae_structure["ode"].size1() if "ode" in self.dae_structure else 0
        n_alg = self.dae_structure["alg"].size1() if "alg" in self.dae_structure else 0
        total_eqs = n_ode + n_alg

        dof = total_vars - total_eqs

        if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
            print(f"\n[{self.model.name} COMPILATION REPORT]")
            print(f"  -> Total Variables: {total_vars} (Differential: {n_x}, Algebraic: {n_z})")
            print(f"  -> Total Equations: {total_eqs} (ODE: {n_ode}, Algebraic: {n_alg})")
            print(f"  -> Degrees of Freedom: {dof}")
            if dof == 0:
                print("  -> Status: System is mathematically closed. OK!\n")

        if dof != 0:
            msg = (
                f"\n[ANTARES MATHEMATICAL KERNEL] Degrees of Freedom Violation!\n"
                f"The transpiled model '{self.model.name}' is not mathematically closed.\n\n"
                f"  -> Total Variables: {total_vars}\n"
                f"  -> Total Equations: {total_eqs}\n"
                f"  -> DOF (Vars - Eqs): {dof}\n\n"
            )
            raise DegreesOfFreedomError(msg)

    def _compile_integrator(self, t_span, use_c_code=False):
        """
        Compiles the CasADi JIT integrator for dynamic simulation.

        :param array-like t_span: 1D array containing the time grid.
        :param bool use_c_code: Internal flag resolving the hierarchy of C code compilation.
        """
        if self._integrator is None or not np.array_equal(t_span, self._last_t_span):
            if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 2:
                print("Compiling CasADi integrator (This occurs only once per time grid)...")

            opts = self.solver_opts.copy()
            t0 = t_span[0]

            if use_c_code:
                if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
                    print(f"[{self.model.name}] Generating and compiling pure C code for extreme performance.")
                
                opts["jit"] = True
                opts["compiler"] = "shell"
                if getattr(cfg, "C_COMPILATION_OPTIMIZATION_LEVEL", "basic") == "aggressive":
                    opts["jit_options"] = {"flags": ["-O3", "-ffast-math"]}
                else:
                    opts["jit_options"] = {"flags": ["-O1", "-pipe"]} 
                
                try:
                    self._integrator = ca.integrator(
                        self._compilation_prefixes[0], self.solver_type, self.dae_structure, t0, t_span, opts
                    )
                except Exception as e:
                    if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
                        warnings.warn(
                            "Native C code compilation failed. Falling back to the CasADi Virtual Machine."
                        )
                    opts["jit"] = False
                    self._integrator = ca.integrator(
                        self._compilation_prefixes[0], self.solver_type, self.dae_structure, t0, t_span, opts
                    )
            else:
                self._integrator = ca.integrator(
                    self._compilation_prefixes[0], self.solver_type, self.dae_structure, t0, t_span, opts
                )

            self._last_t_span = t_span

    def _compile_rootfinder(self, use_c_code=False):
        """
        Compiles the steady-state rootfinder, converting all differential 
        and algebraic equations into a unified zero-residual root search.
        
        :param bool use_c_code: Internal flag for C-code native compilation.
        """
        if self._rootfinder is None:
            if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 2:
                print("Compiling CasADi rootfinder for steady-state analysis...")

            dae = self.dae_structure

            # Combine all unknowns (differential states become steady algebraic variables)
            v_vars = []
            if "x" in dae and dae["x"].size1() > 0: v_vars.append(dae["x"])
            if "z" in dae and dae["z"].size1() > 0: v_vars.append(dae["z"])
            v = ca.vertcat(*v_vars) if v_vars else ca.MX()

            # Combine all residual equations (ode = 0 and alg = 0)
            eq_vars = []
            if "ode" in dae and dae["ode"].size1() > 0: eq_vars.append(dae["ode"])
            if "alg" in dae and dae["alg"].size1() > 0: eq_vars.append(dae["alg"])
            eqs = ca.vertcat(*eq_vars) if eq_vars else ca.MX()

            p = dae["p"] if "p" in dae and dae["p"].size1() > 0 else ca.MX()

            # Format the steady-state problem: g(x, p) = 0
            problem = {'x': v, 'p': p, 'g': eqs}

            opts = {"abstol": getattr(cfg, "DEFAULT_ABSOLUTE_TOLERANCE", 1e-8)}

            if use_c_code:
                if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
                    print(f"[{self.model.name}] Generating and compiling pure C code for Rootfinder.")
                opts["jit"] = True
                opts["compiler"] = "shell"
                if getattr(cfg, "C_COMPILATION_OPTIMIZATION_LEVEL", "basic") == "aggressive":
                    opts["jit_options"] = {"flags": ["-O3", "-ffast-math"]}
                else:
                    opts["jit_options"] = {"flags": ["-O1", "-pipe"]}
                
                try:
                    self._rootfinder = ca.rootfinder(self._compilation_prefixes[1], 'kinsol', problem, opts)
                except Exception as e:
                    if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
                        warnings.warn("Native C code compilation failed for Rootfinder. Falling back to VM.")
                    opts["jit"] = False
                    self._rootfinder = ca.rootfinder(self._compilation_prefixes[1], 'kinsol', problem, opts)
            else:
                self._rootfinder = ca.rootfinder(self._compilation_prefixes[1], 'kinsol', problem, opts)

    def run(self, t_span, initial_conditions=None, parameters_dict=None, use_c_code=None):
        """
        Executes dynamic integration (transients) over a time grid.

        :param array-like t_span: Time grid for the simulation.
        :param dict initial_conditions: Runtime override for variables ICs. Defaults to None.
        :param dict parameters_dict: Runtime override for parameters. Defaults to None.
        :param bool use_c_code: Runtime override to force native C compilation. 
        :return: Results object containing the structured data of the simulation.
        :rtype: Results
        """
        do_c_code = use_c_code if use_c_code is not None else getattr(cfg, "USE_C_CODE_COMPILATION", False)
        ic_dict = initial_conditions if initial_conditions is not None else {}
        p_dict = parameters_dict if parameters_dict is not None else {}

        self._compile_integrator(t_span, use_c_code=do_c_code)

        x0_vec = self._build_input_vector(ic_dict, self.transpiler.x_vars, self.model.variables, category="differential")
        z0_vec = self._build_input_vector(ic_dict, self.transpiler.z_vars, self.model.variables, category="algebraic")
        p_vec  = self._build_input_vector(p_dict, self.transpiler.p_vars, self.model.parameters, category="parameter")

        sim_args = {"x0": x0_vec, "p": p_vec}
        if self.transpiler.z_vars:
            sim_args["z0"] = z0_vec

        res = self._integrator(**sim_args)

        x_res = res["xf"].full().T
        z_res = res["zf"].full().T if self.transpiler.z_vars else None

        results_container = Results(name=f"Sim_{self.model.name}", time_units=getattr(cfg, "DEFAULT_TIME_UNIT", "s"))
        x_names = [var.name() for var in self.transpiler.x_vars]
        z_names = [var.name() for var in self.transpiler.z_vars]

        results_container.load_from_simulator(t_span, x_res, z_res, x_names, z_names)

        # Trigger Housekeeping
        if do_c_code:
            self._cleanup_compilation_files()

        if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
            print("Dynamic Simulation successfully completed!")

        return results_container

    def run_steady_state(self, initial_guesses=None, parameters_dict=None, use_c_code=None):
        """
        Executes a Steady-State solution (Rootfinding) where dx/dt = 0.
        All temporal dynamics are bypassed and the system resolves to its final equilibrium.

        :param dict initial_guesses: Dictionary with initial estimates for numerical convergence.
        :param dict parameters_dict: Runtime override for parameters. Defaults to None.
        :param bool use_c_code: Runtime override to force native C compilation.
        :return: Results object with a single time-point containing the equilibrium state.
        :rtype: Results
        """
        do_c_code = use_c_code if use_c_code is not None else getattr(cfg, "USE_C_CODE_COMPILATION", False)
        ig_dict = initial_guesses if initial_guesses is not None else {}
        p_dict = parameters_dict if parameters_dict is not None else {}

        # 1. Smart Compilation using KINSOL rootfinder
        self._compile_rootfinder(use_c_code=do_c_code)

        # 2. Extract input vectors
        x0_vec = self._build_input_vector(ig_dict, self.transpiler.x_vars, self.model.variables, category="algebraic")
        z0_vec = self._build_input_vector(ig_dict, self.transpiler.z_vars, self.model.variables, category="algebraic")
        
        v0_vec = []
        if x0_vec: v0_vec.extend(x0_vec)
        if z0_vec: v0_vec.extend(z0_vec)

        p_vec = self._build_input_vector(p_dict, self.transpiler.p_vars, self.model.parameters, category="parameter")

        # 3. Execution using Newton-Raphson / KINSOL
        res = self._rootfinder(x0=v0_vec, p=p_vec)

        # 4. Results splitting
        v_sol = res['x'].full().flatten()

        n_x = len(x0_vec)
        x_sol = v_sol[:n_x]
        z_sol = v_sol[n_x:]

        # 5. Packaging into Results container as a single time point (t = 0.0)
        results_container = Results(
            name=f"Steady_{self.model.name}", 
            time_units=getattr(cfg, "DEFAULT_TIME_UNIT", "s")
        )

        x_names = [var.name() for var in self.transpiler.x_vars]
        z_names = [var.name() for var in self.transpiler.z_vars]

        t_ss = np.array([0.0])
        x_res = np.array([x_sol]) if n_x > 0 else np.array([[]])
        z_res = np.array([z_sol]) if len(z_sol) > 0 else None
        
        results_container.load_from_simulator(t_ss, x_res, z_res, x_names, z_names)
        
        # Trigger Housekeeping
        if do_c_code:
            self._cleanup_compilation_files()

        if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
            print("Steady-State solution successfully found!")

        return results_container

    def _build_input_vector(self, input_dict, ca_vars_list, model_dict, category="algebraic"):
        """
        Builds the input numerical vector expected by CasADi, resolving the 
        hierarchy between runtime overrides and model-encapsulated definitions.

        :param dict input_dict: Runtime user-provided overrides.
        :param list ca_vars_list: List of symbolic variables from the transpiler.
        :param dict model_dict: Dictionary containing the original model objects.
        :param str category: Defines strictness logic ("differential" or "algebraic").
        :return: A numerical list populated with initial values or guesses.
        :rtype: list
        :raises AbsentRequiredObjectError: If a differential state lacks an initial condition.
        :raises UnexpectedValueError: If a value cannot be resolved.
        """
        vec = []
        for ca_var in ca_vars_list:
            var_name = ca_var.name()

            if var_name in input_dict:
                vec.append(input_dict[var_name])
            elif category == "differential":
                if var_name in model_dict and getattr(model_dict[var_name], "is_specified", False):
                    vec.append(model_dict[var_name].value)
                else:
                    raise AbsentRequiredObjectError(
                        f"The differential variable '{var_name}' requires an explicit "
                        f"Initial Condition. Please use 'self.setInitialCondition()'."
                    )
            elif var_name in model_dict:
                vec.append(model_dict[var_name].value)
            else:
                if category == "algebraic":
                    if getattr(cfg, "STRICT_MODE", False):
                        raise AbsentRequiredObjectError(
                            f"[STRICT MODE] Missing initial guess for algebraic variable '{var_name}'."
                        )
                    vec.append(0.0)
                else:
                    raise UnexpectedValueError(
                        f"Unable to resolve a numerical value for {category}: '{var_name}'"
                    )

        return vec