# -*- coding: utf-8 -*-

"""
Simulator Module (V5 Native CasADi Architecture).

Defines the Simulator class for the ANTARES framework.
This module receives the phenomenological model, triggers the native C++
DAE Assembler, and orchestrates the numerical resolution using CasADi's
high-performance SUNDIALS integrators and rootfinders.

It features a Smart Dispatcher that introspects the mathematical structure
of the formulated system. If a purely algebraic topology is detected, it
automatically bypasses dynamic integration and resolves the steady-state
roots, propagating the result over the requested timespan to ensure API continuity
without requiring dummy differential states.
"""

import glob
import os
import warnings

import casadi as ca
import numpy as np

import antares.core.GLOBAL_CFG as cfg
from antares.backend.transpiler import CasadiTranspiler
from antares.core.error_definitions import (
    AbsentRequiredObjectError,
    DegreesOfFreedomError,
    UnexpectedValueError,
)
from antares.core.results import Results


class Simulator:
    """
    Orchestrates the numerical resolution of the mathematical model.
    Bridges the declarative Model abstractions with the high-performance
    CasADi backend. Supports both dynamic integration (IDAS) and steady-state
    resolution (KINSOL) of native C++ block-vectorized graphs.
    """

    def __init__(self, model, solver_type=None, check_dof=None):
        """
        Initializes the Simulator context.

        :param Model model: The formulated ANTARES model.
        :param str solver_type: Target solver suite (e.g., 'idas', 'cvodes'). Defaults to GLOBAL_CFG.
        :param bool check_dof: Flag to perform Degrees of Freedom analysis. Defaults to GLOBAL_CFG.
        """
        self.model = model
        self.solver_type = (
            solver_type
            if solver_type is not None
            else getattr(cfg, "DEFAULT_INTEGRATOR", "idas")
        )

        # In V5, the Transpiler acts as a pure DAE Assembler
        self.transpiler = CasadiTranspiler(model)
        self.dae_structure = self.transpiler.transpile()

        do_dof_check = (
            check_dof
            if check_dof is not None
            else getattr(cfg, "PERFORM_DOF_CHECK", True)
        )
        if do_dof_check:
            self._check_degrees_of_freedom()

        self.solver_opts = {
            "calc_ic": True,
            "reltol": getattr(cfg, "DEFAULT_RELATIVE_TOLERANCE", 1e-6),
            "abstol": getattr(cfg, "DEFAULT_ABSOLUTE_TOLERANCE", 1e-8),
        }

        self._integrator = None
        self._rootfinder = None
        self._last_t_span = None
        self._compilation_prefixes = ["jit_", "tmp_casadi_"]

    def _cleanup_compilation_files(self):
        """
        Removes temporary C compilation files generated by CasADi's JIT compiler.
        Behavior is governed by GLOBAL_CFG.KEEP_TEMPORARY_COMPILATION_FILES.
        """
        keep_files = getattr(cfg, "KEEP_TEMPORARY_COMPILATION_FILES", False)
        if keep_files:
            return

        extensions = ["*.c", "*.o", "*.so", "*.dll"]
        for prefix in self._compilation_prefixes:
            for ext in extensions:
                for filepath in glob.glob(f"{prefix}{ext}"):
                    try:
                        os.remove(filepath)
                    except OSError:
                        pass

    def _check_degrees_of_freedom(self):
        """
        Validates the mathematical closure of the assembled DAE system.
        Compares the total number of variables against the total number of equations.

        :raises DegreesOfFreedomError: If the system is not mathematically closed (DOF != 0).
        """
        n_x = self.dae_structure["x"].size1() if "x" in self.dae_structure else 0
        n_z = self.dae_structure["z"].size1() if "z" in self.dae_structure else 0
        total_vars = n_x + n_z

        n_ode = self.dae_structure["ode"].size1() if "ode" in self.dae_structure else 0
        n_alg = self.dae_structure["alg"].size1() if "alg" in self.dae_structure else 0
        total_eqs = n_ode + n_alg

        dof = total_vars - total_eqs

        if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
            print(f"\n[{self.model.name} COMPILATION REPORT]")
            print(
                f"  -> Total Variables: {total_vars} (Differential: {n_x}, Algebraic: {n_z})"
            )
            print(
                f"  -> Total Equations: {total_eqs} (ODE: {n_ode}, Algebraic: {n_alg})"
            )
            print(f"  -> Degrees of Freedom: {dof}")
            if dof == 0:
                print("  -> Status: System is mathematically closed. OK!\n")

        if dof != 0:
            msg = (
                f"\n[ANTARES MATHEMATICAL KERNEL] Degrees of Freedom Violation!\n"
                f"The assembled model '{self.model.name}' is not mathematically closed.\n\n"
                f"  -> Total Variables: {total_vars}\n"
                f"  -> Total Equations: {total_eqs}\n"
                f"  -> DOF (Vars - Eqs): {dof}\n\n"
            )
            raise DegreesOfFreedomError(msg)

    def _resolve_linear_solver(self, requested_solver):
        """
        Translates generic ANTARES intents ('direct', 'iterative') into
        exact CasADi C++ plugin names, applying safe fallbacks for missing libraries.

        :param str requested_solver: The intended solver strategy.
        :return: The CasADi-compatible linear solver plugin name.
        :rtype: str
        """
        req = requested_solver.lower()
        if req == "iterative":
            if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
                print(
                    "\n[ANTARES WARNING] The iterative linear solver plugin ('gmres') is missing from your "
                    "CasADi distribution. Safely falling back to the 'csparse' direct solver, "
                    "which is highly optimized for N-Dimensional sparse matrices.\n"
                )
            return "csparse"
        elif req == "direct":
            return "csparse"

        return req

    def _compile_integrator(self, t_span, use_c_code=False, linear_solver="direct"):
        """
        Compiles the CasADi dynamic integrator (e.g., IDAS) utilizing the assembled DAE structure.

        :param array-like t_span: 1D array of time points for the integration.
        :param bool use_c_code: Flag to trigger native C code JIT compilation.
        :param str linear_solver: The target linear solver strategy.
        """
        if self._integrator is None or not np.array_equal(t_span, self._last_t_span):
            opts = self.solver_opts.copy()
            t0 = t_span[0]

            opts["linear_solver"] = self._resolve_linear_solver(linear_solver)

            if use_c_code:
                opts["jit"] = True
                opts["compiler"] = "shell"
                if (
                    getattr(cfg, "C_COMPILATION_OPTIMIZATION_LEVEL", "basic")
                    == "aggressive"
                ):
                    opts["jit_options"] = {"flags": ["-O3", "-ffast-math"]}
                else:
                    opts["jit_options"] = {"flags": ["-O1", "-pipe"]}
                try:
                    self._integrator = ca.integrator(
                        self._compilation_prefixes[0],
                        self.solver_type,
                        self.dae_structure,
                        t0,
                        t_span,
                        opts,
                    )
                except Exception:
                    opts["jit"] = False
                    self._integrator = ca.integrator(
                        self._compilation_prefixes[0],
                        self.solver_type,
                        self.dae_structure,
                        t0,
                        t_span,
                        opts,
                    )
            else:
                self._integrator = ca.integrator(
                    self._compilation_prefixes[0],
                    self.solver_type,
                    self.dae_structure,
                    t0,
                    t_span,
                    opts,
                )

            self._last_t_span = t_span

    def _compile_rootfinder(self, use_c_code=False, linear_solver="direct"):
        """
        Compiles the CasADi rootfinder (e.g., KINSOL) for steady-state resolution.

        :param bool use_c_code: Flag to trigger native C code JIT compilation.
        :param str linear_solver: The target linear solver strategy.
        """
        if self._rootfinder is None:
            dae = self.dae_structure

            v_vars = []
            if "x" in dae and dae["x"].size1() > 0:
                v_vars.append(dae["x"])
            if "z" in dae and dae["z"].size1() > 0:
                v_vars.append(dae["z"])
            v = ca.vertcat(*v_vars) if v_vars else ca.MX()

            eq_vars = []
            if "ode" in dae and dae["ode"].size1() > 0:
                eq_vars.append(dae["ode"])
            if "alg" in dae and dae["alg"].size1() > 0:
                eq_vars.append(dae["alg"])
            eqs = ca.vertcat(*eq_vars) if eq_vars else ca.MX()

            p = dae["p"] if "p" in dae and dae["p"].size1() > 0 else ca.MX()
            problem = {"x": v, "p": p, "g": eqs}

            opts = {"abstol": getattr(cfg, "DEFAULT_ABSOLUTE_TOLERANCE", 1e-8)}
            opts["linear_solver"] = self._resolve_linear_solver(linear_solver)

            if getattr(cfg, "ROOTFINDER_SOLVER_DEBUG_LEVEL ", 0) >= 3:
                opts["print_level"] = 3

            if use_c_code:
                opts["jit"] = True
                opts["compiler"] = "shell"
                opts["jit_options"] = {"flags": ["-O1", "-pipe"]}
                try:
                    self._rootfinder = ca.rootfinder(
                        self._compilation_prefixes[1], "kinsol", problem, opts
                    )
                except Exception:
                    opts["jit"] = False
                    self._rootfinder = ca.rootfinder(
                        self._compilation_prefixes[1], "kinsol", problem, opts
                    )
            else:
                self._rootfinder = ca.rootfinder(
                    self._compilation_prefixes[1], "kinsol", problem, opts
                )

    def _get_initial_vector(self, input_dict, category="differential"):
        """
        Extracts the numerical Initial Conditions, natively mapping the Vector Blocks.

        :param dict input_dict: User-provided dictionary of explicit initial values.
        :param str category: Type of variables to extract ('differential' or 'algebraic').
        :return: Ordered list containing the numerical initial values.
        :rtype: list
        :raises AbsentRequiredObjectError: If a differential variable lacks an initial condition.
        """
        vec = []
        for var_name, var_obj in self.model.variables.items():
            if getattr(var_obj, "is_distributed", False):
                ic_arr = var_obj.initial_condition_array
                if category == "differential" and var_obj.idx_diff:
                    vec.extend(ic_arr[var_obj.idx_diff].tolist())
                elif category == "algebraic" and var_obj.idx_alg:
                    vec.extend(ic_arr[var_obj.idx_alg].tolist())
            else:
                if var_obj.type == category:
                    if var_name in input_dict:
                        vec.append(input_dict[var_name])
                    elif category == "differential":
                        if getattr(var_obj, "is_specified", False):
                            vec.append(var_obj.value)
                        else:
                            raise AbsentRequiredObjectError(
                                f"Differential variable '{var_name}' requires an Initial Condition."
                            )
                    else:
                        vec.append(var_obj.value)
        return vec

    def _get_parameter_vector(self, p_dict):
        """
        Extracts parameter values strictly preserving the Assembler's topological order.

        :param dict p_dict: User-provided dictionary of explicit parameter overrides.
        :return: Ordered list containing the numerical parameter values.
        :rtype: list
        """
        vec = []
        for par_name, par_obj in self.model.parameters.items():
            if par_name in p_dict:
                vec.append(p_dict[par_name])
            else:
                vec.append(par_obj.value)
        return vec

    def _generate_names_list(self):
        """
        Flattens multi-dimensional topological coordinates back into explicit string names.

        :return: A tuple containing lists of names for differential and algebraic variables.
        :rtype: tuple(list, list)
        """
        x_names, z_names = [], []
        for var_name, var_obj in self.model.variables.items():
            if getattr(var_obj, "is_distributed", False):
                for i in range(var_obj.n_points):
                    idx_tuple = np.unravel_index(i, var_obj.tensor_shape)
                    idx_str = "_".join(map(str, idx_tuple))
                    node_name = f"{var_name}_{var_obj.domain.name}_{idx_str}"
                    if i in var_obj.idx_diff:
                        x_names.append(node_name)
                    if i in var_obj.idx_alg:
                        z_names.append(node_name)
            else:
                if var_obj.type == "differential":
                    x_names.append(var_name)
                else:
                    z_names.append(var_name)
        return x_names, z_names

    def run(
        self,
        t_span,
        initial_conditions=None,
        parameters_dict=None,
        use_c_code=None,
        linear_solver=None,
    ):
        """
        Executes the resolution of the assembled DAE system over the specified time span.

        Features a Smart Dispatcher algorithm: If the model is completely algebraic
        (zero differential states), it automatically intercepts the execution, bypasses
        the dynamic integrator (IDAS), and utilizes the Rootfinder (KINSOL). The steady-state
        solution is then dynamically propagated over the specified `t_span` to mimic temporal
        continuity without relying on numerical dummy-hacks.

        :param array-like t_span: 1D array of time points for integration.
        :param dict initial_conditions: Explicit mapping of variable names to initial values.
        :param dict parameters_dict: Explicit mapping of parameter names to specific values.
        :param bool use_c_code: Overrides the global JIT compilation setting.
        :param str linear_solver: Overrides the global linear solver setting.
        :return: A container holding the integrated temporal trajectories.
        :rtype: Results
        """
        n_x = self.dae_structure["x"].size1() if "x" in self.dae_structure else 0

        # =====================================================================
        # SMART DISPATCHER: Intercepts Pure Algebraic Systems (Steady-State)
        # =====================================================================
        if n_x == 0:
            if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
                print(
                    "\n[SMART DISPATCHER] No differential variables detected (nx = 0)."
                )
                print(
                    "Intercepting dynamic integration and routing directly to KINSOL Rootfinder..."
                )

            do_c_code = (
                use_c_code
                if use_c_code is not None
                else getattr(cfg, "USE_C_CODE_COMPILATION", False)
            )
            do_lin_sol = (
                linear_solver
                if linear_solver is not None
                else getattr(cfg, "DEFAULT_LINEAR_SOLVER", "direct")
            )

            ig_dict = initial_conditions if initial_conditions is not None else {}
            p_dict = parameters_dict if parameters_dict is not None else {}

            self._compile_rootfinder(use_c_code=do_c_code, linear_solver=do_lin_sol)

            z0_vec = self._get_initial_vector(ig_dict, category="algebraic")
            p_vec = self._get_parameter_vector(p_dict)

            if getattr(cfg, "ROOTFINDER_SOLVER_DEBUG_LEVEL ", 0) >= 3:
                # =================================================================
                # INJEÇÃO DE DEBUG CIRÚRGICO: RAIO-X DOS RESÍDUOS INICIAIS
                # =================================================================
                print("\n" + "=" * 70)
                print(" DIAGNÓSTICO DE RESÍDUOS (t=0) ANTES DO KINSOL ")
                print("=" * 70)
                try:
                    # 1. Extrair os símbolos diretamente do Assembler do Antares
                    v_sym = self.dae_structure["z"]
                    p_sym = (
                        self.dae_structure["p"]
                        if "p" in self.dae_structure
                        else ca.MX()
                    )
                    g_sym = self.dae_structure["alg"]

                    # 2. Criar uma Função CasADi explícita para as equações (g)
                    calc_res = ca.Function("calc_res", [v_sym, p_sym], [g_sym])

                    # 3. Avaliar numericamente usando os exatos chutes iniciais
                    residuos = calc_res(z0_vec, p_vec).full().flatten()

                    print("Vetor de Resíduos Iniciais F(x0):")
                    for i, valor in enumerate(residuos):
                        # Destacar visualmente onde a matriz quebrou
                        if np.isnan(valor) or abs(valor) > 1000:
                            print(
                                f" -> Eq [{i}]: {valor: .6e}  <---
                            )
                        else:
                            print(f"    Eq [{i}]: {valor: .6e}")
                except Exception as e:
                    print(f"Falha ao avaliar resíduos: {e}")
                print("=" * 70 + "\n")
                # =================================================================

            res = self._rootfinder(x0=z0_vec, p=p_vec)
            z_sol = res["x"].full().flatten()

            results_container = Results(
                name=f"Sim_{self.model.name}",
                time_units=getattr(cfg, "DEFAULT_TIME_UNIT", "s"),
            )
            x_names, z_names = self._generate_names_list()

            # Broadcast the steady-state solution across the entire requested time span
            n_t = len(t_span)
            x_res = np.empty((n_t, 0))
            z_res = np.tile(z_sol, (n_t, 1))

            results_container.load_from_simulator(
                t_span, x_res, z_res, x_names, z_names
            )

            if do_c_code:
                self._cleanup_compilation_files()
            if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
                print(
                    "Steady-State roots evaluated and propagated over the timespan successfully!\n"
                )

            return results_container

        # =====================================================================
        # STANDARD EXECUTION: Dynamic DAE Integration (nx > 0)
        # =====================================================================
        do_c_code = (
            use_c_code
            if use_c_code is not None
            else getattr(cfg, "USE_C_CODE_COMPILATION", False)
        )
        do_lin_sol = (
            linear_solver
            if linear_solver is not None
            else getattr(cfg, "DEFAULT_LINEAR_SOLVER", "direct")
        )

        ic_dict = initial_conditions if initial_conditions is not None else {}
        p_dict = parameters_dict if parameters_dict is not None else {}

        self._compile_integrator(t_span, use_c_code=do_c_code, linear_solver=do_lin_sol)

        x0_vec = self._get_initial_vector(ic_dict, category="differential")
        z0_vec = self._get_initial_vector(ic_dict, category="algebraic")
        p_vec = self._get_parameter_vector(p_dict)

        sim_args = {"x0": x0_vec, "p": p_vec}
        if z0_vec:
            sim_args["z0"] = z0_vec

        res = self._integrator(**sim_args)

        x_res = res["xf"].full().T
        z_res = res["zf"].full().T if z0_vec else None

        results_container = Results(
            name=f"Sim_{self.model.name}",
            time_units=getattr(cfg, "DEFAULT_TIME_UNIT", "s"),
        )
        x_names, z_names = self._generate_names_list()

        results_container.load_from_simulator(t_span, x_res, z_res, x_names, z_names)

        if do_c_code:
            self._cleanup_compilation_files()
        if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
            print("Dynamic Simulation successfully completed!")

        return results_container

    def run_steady_state(
        self,
        initial_guesses=None,
        parameters_dict=None,
        use_c_code=None,
        linear_solver=None,
    ):
        """
        Executes an explicit steady-state resolution (Rootfinding) of the assembled DAE system.
        Derivatives of any existent dynamic variables are internally zeroed, and all constraints
        are treated as an algebraic rootfinding problem.

        :param dict initial_guesses: Explicit mapping of variable names to initial numerical guesses.
        :param dict parameters_dict: Explicit mapping of parameter names to specific values.
        :param bool use_c_code: Overrides the global JIT compilation setting.
        :param str linear_solver: Overrides the global linear solver setting.
        :return: A container holding the steady-state solution vector at an arbitrary t=0.
        :rtype: Results
        """
        do_c_code = (
            use_c_code
            if use_c_code is not None
            else getattr(cfg, "USE_C_CODE_COMPILATION", False)
        )
        do_lin_sol = (
            linear_solver
            if linear_solver is not None
            else getattr(cfg, "DEFAULT_LINEAR_SOLVER", "direct")
        )

        ig_dict = initial_guesses if initial_guesses is not None else {}
        p_dict = parameters_dict if parameters_dict is not None else {}

        self._compile_rootfinder(use_c_code=do_c_code, linear_solver=do_lin_sol)

        x0_vec = self._get_initial_vector(ig_dict, category="differential")
        z0_vec = self._get_initial_vector(ig_dict, category="algebraic")

        v0_vec = []
        if x0_vec:
            v0_vec.extend(x0_vec)
        if z0_vec:
            v0_vec.extend(z0_vec)

        p_vec = self._get_parameter_vector(p_dict)

        res = self._rootfinder(x0=v0_vec, p=p_vec)

        v_sol = res["x"].full().flatten()
        n_x = len(x0_vec)
        x_sol = v_sol[:n_x]
        z_sol = v_sol[n_x:]

        results_container = Results(
            name=f"Steady_{self.model.name}",
            time_units=getattr(cfg, "DEFAULT_TIME_UNIT", "s"),
        )
        x_names, z_names = self._generate_names_list()

        t_ss = np.array([0.0])
        x_res = np.array([x_sol]) if n_x > 0 else np.array([[]])
        z_res = np.array([z_sol]) if len(z_sol) > 0 else None

        results_container.load_from_simulator(t_ss, x_res, z_res, x_names, z_names)

        if do_c_code:
            self._cleanup_compilation_files()
        if getattr(cfg, "VERBOSITY_LEVEL", 1) >= 1:
            print("Steady-State solution successfully found!")

        return results_container
